version: '3.1'

services:
  app:
    container_name: spring_blog
    build: .
    ports:
      - 8080:8080
    restart: always
    links:
      - mongo
  mongo:
    container_name: mongo_spring
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passroot
      MONGO_INITDB_DATABASE: mongoBlog
